---
# tasks file for kubernetes
- name: Install packages for Debian based environments
  apt:
    update_cache: yes
    name:
      - lvm2
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


