---
# tasks file for kubernetes
- name: Install packages for Debian based environments
  apt:
    update_cache: yes
    name:
      - lvm2
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- sysctl:
    # https://www.ibm.com/docs/en/aspera-on-demand/3.9?topic=line-configuring-linux-many-watch-folders
    # https://github.com/kubernetes/kubernetes/issues/64315#issuecomment-904103310
    # /proc/sys/fs/inotify/max_user_watches - 524288
    name: fs.inotify.max_user_watches
    value: "1048576"
    state: present
    reload: yes

- sysctl:
    # https://www.ibm.com/docs/en/aspera-on-demand/3.9?topic=line-configuring-linux-many-watch-folders
    # https://github.com/kubernetes/kubernetes/issues/64315#issuecomment-904103310
    # /proc/sys/fs/inotify/max_user_instances  128
    name: fs.inotify.max_user_instances
    value: "1024"
    state: present
    reload: yes



